create table if not exists locations (
  id bigint generated by default as identity primary key,
  name text not null unique
);
create table if not exists members (
  id bigint generated by default as identity primary key,
  name text not null unique,
  role text
);
create table if not exists accounts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null check (type in ('bank','credit','cash','other'))
);
create table if not exists rules (
  id bigint generated by default as identity primary key,
  name text not null,
  match text not null,
  category text not null
);
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  date date not null,
  description text not null,
  amount numeric not null,
  account_id bigint references accounts(id) on delete set null,
  location_id bigint references locations(id) on delete set null,
  member_id bigint references members(id) on delete set null,
  category text
);
